* OpenCV 的开发环境搭建


** Mac \+ Xcode 的 OpenCV 环境搭建

*** 安装 OpenCV
   
   使用 brew 工具安装 OpenCV,默认已经安装了 brew，如果没有安装参考网上的教程，很容易安装好。
   
   .. code-block:: shell
   
       brew install opencv 

   [注]网上有教程说，使用 brew install opencv 是安装的 2.4 的版本，``brew install opencv3``是安装 3.x 的最新版本。但是笔者
   当时使用的是``brew install opencv``安装的是 3.4 版本的。

*** 配置 Xcode 环境
   
   由于使用 brew 工具下载的项目都是放置在``/usr/local/Cellar``目录下得所以查看是否安装成功就是这个目录下的``opencv``目录，检查``lib``和``include``中是否有文件。

   新建项目选择``macOS``，``Command Line Tool``,``C++``项目,打开项目文件名配置环境变量

   + ``Build Phases``的配置中``Link Binary With Libraries``点开下拉框点击``+``从``/usr/local/Cellar/opencv/lib``添加\*.dylib 库文件
   + ``Build Settings``中的``Search Paths``配置``Header Search Paths``添加为``/usr/local/include``并且将``Library Search Paths``中添为``/usr/local/lib``

*** 使用 Opencv 的例子代码测试是否运行成功  

** 图像分割
   图像分成若干个特定的，具有独特性质的区域，每个区域代表一个像素的集合，每一个集合
   又代表一个物体，而完成该过程的技术通常称为图像分割。

*** 图像分割方法主要分为几类
   - 基于阈值分割方法
   - 基于区域的分割方法
   - 基于边缘的分割方法

*** 基于阈值分割的结果是：
    - 阈值分割后的输出图像只有两种灰度值：255 和 0，所以阈值分割处理又称为二值化处理。
    - 阈值分割处理主要是根据灰度值提取前景，对前景物体和背景物体有较强对比度图像的分割特别有用。

*** 基于阈值分割的方式有分类：

    - 全局阈值分割：将灰度值大于 thresh 的像素设为白色，小于或者等于 thresh 的像素设为黑色。
    - 自适应局部阈值分割：移动平均值算法，是一种简单但是高效的局部阈值算法，核心思想就是把每个像素的邻域的平均值作为阈值。

*** 阈值分割的核心：
    - 如何选取阈值或阈值矩阵，选取正确的阈值是分割成功的关键。

*** 阈值的分类：

    - 全局阈值
    - 矩阵阈值(和输入矩阵相同尺寸的矩阵 thresh)

** 直方图技术法

